# Deploy to prod

name: Deploy Production
permissions:
  contents: read
  pages: write
  id-token: write

on:
  repository_dispatch:
    types: [production_deploy]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production mirror repo
        uses: actions/checkout@v3

      - name: Checkout secondlane-tma repo
        uses: actions/checkout@v3
        with:
          repository: matt-secondlane/secondlane-tma
          ref: ${{ github.event.client_payload.tag }}
          path: tma-source

      - name: Copy TMA files
        run: |
          # Save the .git directory
          mv .git git-backup
          # Remove everything except tma-source and git-backup
          find . -mindepth 1 -maxdepth 1 ! -name 'tma-source' ! -name 'git-backup' -exec rm -rf {} +
          # Copy TMA files
          cp -r tma-source/* ./
          # Restore .git
          rm -rf .git
          mv git-backup .git
          # Clean up
          rm -rf tma-source

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set environment variables
        run: |
          # Production deployment for tags
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
          echo "SECONDLANE_API_URL=https://prod.secondlane.io" >> $GITHUB_ENV

      - name: Create env file
        run: |
          echo "VITE_SECONDLANE_API_URL=${{ env.SECONDLANE_API_URL }}" >> .env
          echo "VITE_API_URL=http://127.0.0.1:5173" >> .env
          echo "VITE_IS_TEST_ENV=false" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:${{ env.ENVIRONMENT }}

      - name: Log deployment info
        run: |
          echo "Deploying to ${{ env.ENVIRONMENT }} environment"
          echo "Using API URL: ${{ env.SECONDLANE_API_URL }}"
          echo "Deploying tag: ${{ github.event.client_payload.tag }}"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

